### ISSUE TITLE
Cannot compile. Failing on cross compiling check

### ISSUE THREAD

**Issue by vlakam** [M-Reimer/wine-lol#10]
Whether using makepkg or yay
```
  -> Building Wine-32...
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/home/petrovich/.cache/yay/wine-lol/src/wine-lol-32-build':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```
[config.log](https://github.com/M-Reimer/wine-lol/files/3219968/config.log)

**Comment by xsoalokinx** [comment]
same issue here.
5.1.4-arch1-1-ARCH

**Comment by M-Reimer** [comment]
Did you recompile wine-lol-glibc first? The installation path is different in the new version of wine-glibc.

**Comment by vlakam** [comment]
Yes i did. Still no effect. Compiled binary on Manjaro, gonna use it on my Arch build.

**Comment by M-Reimer** [comment]
Maybe someone else can debug this.
Compiles fine for me and according to the feedback it also worked for several other users.
So something on your systems seems to be "special".

**Comment by HiiroSakaki** [comment]
Check your version of the patched glibc, as I recompiled it just now, it appeared there was some modification as the net upgrate was not zero, and now wine-lol is compiling while I had the issue before

**Comment by vlakam** [comment]
I'm sorry for the inconvience, the problem solved after i updated packages.
