### ISSUE TITLE
wine-lol-glibc in the repo is outdated

### ISSUE THREAD

**Issue by alfzki** [M-Reimer/wine-lol#102]
The package in the repo is still on 2.33, while gamemode require >=glibc-2.34.

**Comment by M-Reimer** [comment]
I know but I currently don't have the time to do the building, signing and finally the uploading with my slow internet connection. At some time I will update the binary but this may take some more days.

My recommendation is that you build from AUR. There the PKGBUILD is already updated and glibc is actually the package of the two which is faster to build.

**Comment by M-Reimer** [comment]
Mass closing issues. My PKGBUILD builds a much more recent wine version now so some issues may be obsolete now.
