### ISSUE TITLE
bug installing from arch linux repo

### ISSUE THREAD

**Issue by obnoxiousish** [M-Reimer/wine-lol#103]
<command-line>: warning: "_FORTIFY_SOURCE" redefined
<command-line>: note: this is the location of the previous definition
during RTL pass: sched2
../../../wine-lol/dlls/d3dx9_29/../d3dx9_36/texture.c: In function ‘D3DXCreateCubeTextureFromFileInMemoryEx’:
../../../wine-lol/dlls/d3dx9_29/../d3dx9_36/texture.c:1524:1: internal compiler error: Segmentation fault
 1524 | }
      | ^
0xd9394a internal_error(char const*, ...)
        ???:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.archlinux.org/> for instructions.
make[1]: *** [Makefile:1109: texture.o] Error 1
make[1]: Leaving directory '/home/o/.cache/yay/wine-lol/src/wine-lol-32-build/dlls/d3dx9_29'
make: *** [Makefile:9310: dlls/d3dx9_29] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: wine-lol

**Comment by M-Reimer** [comment]
Actually a segmentation fault makes no sense here. Would be a compiler error in this case. Did you try cleaning up and building a second time?

**Comment by M-Reimer** [comment]
The repo is not up to date. You have to compile at least wine-lol-glibc on your own.

**Comment by obnoxiousish** [comment]
whatever i have a windows dual boot already anyway i just wanted to save myself some rebooting but its not worth the trouble
