### ISSUE TITLE
how can I change the input language?

### ISSUE THREAD

**Issue by sephid86** [M-Reimer/wine-lol#105]
Thank you for your efforts in making lol running on Linux.

I'm a Korean.

I can't change the input language in wine-lol.

Only English input is allowed.

I've tested it on notepad and all are.

In general wine, can change the input language.

The key to change the input language is the right Alt key.

How can I change the input language?

**Comment by sephid86** [comment]
답변 주셔서 감사합니다.
Thanks for your reply.

알려주신 방법은 이미 시도해본 방법이었고 작동하지 않습니다.
The method you gave is the one I've already tried and it doesn't work.

그리고 나는 방법을 찾았습니다.
And I found a way.

영어 이외에 다른 언어를 사용하는 국가의 사용자들을 위해 내가 찾은 방법의 내용을 공유 합니다.
I'm sharing what I found out for users in countries who speak languages ​​other than English.

아래의 한줄 명령어를 통해 레지스트리에 내용을 추가하면 됩니다.
You can add the contents to the registry using the one-line command below.

다시한번 리눅스에서 리그오브레전드를 플레이 할수 있게 해주신 당신의 노력에 진심으로 감사드립니다.
Once again, thank you very much for your hard work in making League of Legends playable on Linux.



$ WINEPREFIX=~/.local/share/leagueoflegends/ /opt/wine-lol/bin/wine reg add "HKEY_CURRENT_USER\Software\Wine\X11 Driver" /v UseXIM /t REG_SZ /d Y /f

**Comment by sephid86** [comment]
> The "right Alt key" is a hotkey of your desktop environment and not related to Wine itself.
> 
> Probably what you see here is a conflict between "wine-lol-glibc" and the system glibc. All system libraries use "/usr/share/locale" as their locale directory. I also compile wine-lol-glibc to use this as all the system libraries, that we also want to use for wine-lol, have this path compiled in.
> 
> BUT: The story is different for wine-lol itself. As everything "wine-lol related" is placed below /opt/wine-lol, we have another locale path where wine-lol-glibc actually does not know about.
> 
> The documentation mentions a "LOCPATH" environment variable: https://www.gnu.org/software/libc/manual/html_node/Locale-Names.html
> 
> So what **may** help here is if you open LoL from a terminal and before actually launching LoL, please try the following to export LOCPATH:
> 
> `export LOCPATH=/opt/wine-lol/usr/share/locale`

답변 주셔서 감사합니다.
Thanks for your reply.

알려주신 방법은 이미 시도해본 방법이었고 작동하지 않습니다.
The method you gave is the one I've already tried and it doesn't work.

그리고 나는 방법을 찾았습니다.
And I found a way.

영어 이외에 다른 언어를 사용하는 국가의 사용자들을 위해 내가 찾은 방법의 내용을 공유 합니다.
I'm sharing what I found out for users in countries who speak languages ​​other than English.

아래의 한줄 명령어를 통해 레지스트리에 내용을 추가하면 됩니다.
You can add the contents to the registry using the one-line command below.

다시한번 리눅스에서 리그오브레전드를 플레이 할수 있게 해주신 당신의 노력에 진심으로 감사드립니다.
Once again, thank you very much for your hard work in making League of Legends playable on Linux.

$ WINEPREFIX=~/.local/share/leagueoflegends/ /opt/wine-lol/bin/wine reg add "HKEY_CURRENT_USER\Software\Wine\X11 Driver" /v UseXIM /t REG_SZ /d Y /f

**Comment by sephid86** [comment]
There is another problem with the method I shared above.
The chat window does not open with 'enter' once.
And the text hint window is displayed.


In the latest version of wine, you do not need to register usexim in the registry.
Keyboard input in other languages ​​works fine. (tested notepad)

Of course, league of legends will not run in other wines.

I'd appreciate it if you could someday take a look at this issue.

**Comment by M-Reimer** [comment]
> I'd appreciate it if you could someday take a look at this issue.

Sorry but I can't. I am no Wine developer and so have absolutely no insights into how Wine works. I even fail to port the compatibility patch, that we need to make LoL happy, to newer Wine versions. What we really need here is someone with the needed knowledge. But as those people, who have the needed knowledge, think that patching glibc is "too complicated", noone cares about this patch.

**Comment by sephid86** [comment]
> > I'd appreciate it if you could someday take a look at this issue.
> 
> Sorry but I can't. I am no Wine developer and so have absolutely no insights into how Wine works. I even fail to port the compatibility patch, that we need to make LoL happy, to newer Wine versions. What we really need here is someone with the needed knowledge. But as those people, who have the needed knowledge, think that patching glibc is "too complicated", noone cares about this patch.

nonono

sir why are you sorry

I'm sorry for bringing up a difficult story.

https://aur.archlinux.org/packages/wine-lol-staging
In the link above, wine is the latest version and Korean input works well, but if vsyscall is set to 0, the system becomes too slow

After selecting a champion and loading it, it crashes immediately after switching to the actual game screen.

I have no choice but to endure the inconvenience... I will use sir's program.

Thank you for your kind and quick reply.
-----
nonono

sir이 왜 죄송합니까

어려운 이야기를 꺼내어 제가 죄송합니다.

https://aur.archlinux.org/packages/wine-lol-staging
위의 링크는 wine 이 최신버전이고 한글 입력이 잘 작동 하지만 vsyscall 을 0 으로 하면 시스템이 너무 느려지고

챔피언 선택후 로딩이 끝난후 실제 게임화면에 전환된 직후 crash 됩니다.

어쩔수가 없네요.. 그냥 불편함을 감수하는수밖에... 저는 sir 의 프로그램을 이용할것입니다.
