### ISSUE TITLE
2-4 second freeze in game

### ISSUE THREAD

**Issue by solidflame** [M-Reimer/wine-lol#108]
About a month ago the LOL patch 12.11 came out. Every game, once per game, freezes ~4 seconds, between 5-12 minutes the game (Summoner's Rift / ARAM). Training tool - no freeze. There is a similar issue in 7.0-GE-2-LoL, but the freeze duration is 0.5 seconds.
Reddit [here](https://www.reddit.com/r/leagueoflinux/comments/veryr6/querydiscussion_1211_having_a_23_second_freeze/) and [here](https://www.reddit.com/r/leagueoflinux/comments/vr7i8x/short_game_freeze_23_seconds_huge_performance_hit/).
Game Freeze log moment:
> fixme:mountmgr:query_property Faking StorageDeviceProperty data
> fixme:mountmgr:harddisk_ioctl The DISK_PARTITION_INFO and DISK_DETECTION_INFO structures will not be filled

When the game freezes. the mouse and display manager work fine, the CPU and GPU are resting.

**Comment by M-Reimer** [comment]
Not much I can do to help here

**Comment by Miusaky** [comment]
I don't think this issue differs between wine builds. Seems to happen to _everyone_ on Linux. I run wine-lol and the freeze is not ~4 seconds but closer to 0.5.

**Comment by M-Reimer** [comment]
Mass closing issues. My PKGBUILD builds a much more recent wine version now so some issues may be obsolete now.
