### ISSUE TITLE
Consider using the alternate patch

### ISSUE THREAD

**Issue by rafifos** [M-Reimer/wine-lol#11]
Andrew developed another patch a couple days after the first two (the glibc-one and the wine-one), it's a hack but it's simpler than what we have right now because it doesn't need to patch glibc.

But there is a catch, it may require the user to disable vsyscall32, as stated here: https://bugs.winehq.org/show_bug.cgi?id=47198#c40

See: https://bugs.winehq.org/show_bug.cgi?id=47198#c39

**Comment by M-Reimer** [comment]
And exactly that's the reason why I won't use it. Disabling vsyscall32 reduces 32bit performance.
And for me the glibc variant works pretty well.
