### ISSUE TITLE
`wine-lol-glibc` AUR package install quits with an error

### ISSUE THREAD

**Issue by Zedespook** [M-Reimer/wine-lol#110]
I have been using the AUR package, `wine-lol-glibc`, for quite a while now. For some reason on my new install, I get the following compilation error:

```bash
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/../../../../lib32/libstdc++.so: undefined reference to `arc4random@GLIBC_2.36'
collect2: error: ld returned 1 exit status
make[2]: *** [../Rules:230: /home/zedespook/.cache/yay/wine-lol-glibc/src/lib32-glibc-build/support/links-dso-program] Error 1
make[2]: Leaving directory '/home/zedespook/.cache/yay/wine-lol-glibc/src/glibc-2.35/support'
make[1]: *** [Makefile:483: support/others] Error 2
make[1]: Leaving directory '/home/zedespook/.cache/yay/wine-lol-glibc/src/glibc-2.35'
make: *** [Makefile:9: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: wine-lol-glibc
```

**Comment by Zedespook** [comment]
https://github.com/M-Reimer/wine-lol/commit/e9c6395afa1c7dcadd710ab4dc3ed80f33d04901 I didn't see this commit. Sorry for the bother.

**Comment by Zedespook** [comment]
Nevermind, this problem is even present with the prebuilts, anything I can do to resolve the issue?

**Comment by M-Reimer** [comment]
Rebuild from source (only wine-lol) and uninstall wine-lol-glibc. You have to use my latest GIT version of the wine-lol PKGBUILD. But I'm planning to rework this again. So maybe just wait a bit longer.

**Comment by Zedespook** [comment]
Yeah I have no clue on how to build with a custom PKGBUILD. I'm just going to wait for you to push the update to AUR.

**Comment by M-Reimer** [comment]
AUR is updated now.

Please **uninstall** wine-lol-glibc. It is no longer needed!
