### ISSUE TITLE
access to deb packages

### ISSUE THREAD

**Issue by gweio5u4** [M-Reimer/wine-lol#113]
Hi, i know this section is not for that kind of direct questions, but just want to know where can i access the packages previously available at [m-reimer.de/wine-lol/debian/](https://m-reimer.de/wine-lol/debian/)"

**Comment by M-Reimer** [comment]
They are no longer needed. The later versions of "wine-lol" are no longer built by me. Please have a closer look at the project [README.md](https://github.com/M-Reimer/wine-lol/blob/master/README.md).

The PKGBUILDs are meant to provide a way to self-compile wine-lol for Arch users. Everyone else should just download a prebuilt binary directly from GloriousEggroll.

**Comment by gweio5u4** [comment]
Ok, thanks for explanations
