### ISSUE TITLE
New 64-bit not working

### ISSUE THREAD

**Issue by memand** [M-Reimer/wine-lol#114]
Works until entering a game, when it tries to launch the game it crashes and gives this crash dump:

https://0x0.st/HXHt.tmp

**Comment by M-Reimer** [comment]
Not my topic anymore. All the PKGBUILDs do, is package the work done by GloriousEggroll. Maybe try to ask here: https://github.com/GloriousEggroll/wine-ge-custom/

**Comment by memand** [comment]
I found out that this is probably not the completely correct project..

I posted here https://github.com/kyechou/leagueoflegends/issues/83
