### ISSUE TITLE
patch 13.7 lol remove 32bit support.

### ISSUE THREAD

**Issue by yuiiio** [M-Reimer/wine-lol#115]
so currently cs register hacks for fake 32bit architecture is no longer works,

maybe we should back to gs hacks, (need patched glibc again).

I tryed to apply awesie's seccomp patch to upstream wine,
https://bugs.winehq.org/attachment.cgi?id=64481&action=diff
but failed because wine no longer have hook on thread_init().

so I kept 5.18-tkg branch for gs + glibc hacks,

another problem,
need 64bit support for wine-lol but installer and other component is still need 32bit support.
so  need both support 32bit and 64bit.
but, I don't know how to set dynamic linker to ld-linux 
for both 32bit and 64bit.

**Comment by M-Reimer** [comment]
Very likely duplicate of #114

**Comment by yuiiio** [comment]
ok

**Comment by M-Reimer** [comment]
As far as I see, this could be an issue that also exists for many Windows users, currently. Maybe it gets resolved by Riot.

The "old fix", which involved the "separate glibc" was 32 bit only. It would do nothing for 64 bit software. And as far as I remember the issue actually was that Riot used 32 bit for their anticheat. Maybe we can use even less hacks once the new LoL version actually is stable.

And overall: I'm actually pretty happy that the main work for providing a "LoL compatible" wine version is now done by GloriousEggroll. I'm no wine developer and I don't have any experience with how wine internally works. GloriousEggroll has much better knowledge there. I've also stopped playing LoL myself years ago and I don't plan to start playing again.

As soon as a new version is published by GloriousEggroll, I'll happily update my PKGBUILDs.
