### ISSUE TITLE
Manjaro FreeType Error

### ISSUE THREAD

**Issue by Naginipython** [M-Reimer/wine-lol#118]
I'm trying to build wine-lol on Manjaro KDE, and I'm running into the following issue:
`configure: error: FreeType 64-bit development files not found. Fonts will not be built.`
I've attempted to read about solutions to this from the past, and I find that my glibc is version 2.37-2, which I am unsure matters.

Specs:
OS: Manjaro Linux x86_64 
Kernel: 6.1.25-1-MANJARO 
DE: Plasma 5.27.4 
CPU: Intel i7-4790K (8) @ 4.400GHz 
GPU: NVIDIA GeForce GTX 1070 Ti

**Comment by M-Reimer** [comment]
I guess you can safely ignore this.

Is "freetype" installed?

**Comment by Naginipython** [comment]
I have freetype2 2.13.0-1 installed. It's also worth noting that wine-lol-bin did work, I don't know the difference between the two, however

**Comment by M-Reimer** [comment]
As the latest version can be built, I guess this is resolved.
