### ISSUE TITLE
Can't build : ld error during a cross compilation

### ISSUE THREAD

**Issue by sinxn** [M-Reimer/wine-lol#12]
Hello,
As suggested by M-Reimer I move here a comment I made on the AUR.
I can't manage to build wine-lol. During something that appears to be a cross-compilation the mingw linker can't find -lgcc and -lgcc_eh. I already installed wine-lol-glibc but still have this error. What do I need to install to satisfy these dependencies ? I don't know exactly what lgcc(_eh) stands for.

Precisions : 
-I use "standard" Archlinux
-I did not use any AUR helper

Thanks for help

**Comment by M-Reimer** [comment]
Can you copy the relevant part of the build messages please and attach them as log file?

**Comment by sinxn** [comment]
Here is what I get after something like 5 minutes of compilation. It seems to appear during the execution of "tools/mekedep".
I put the build messages directly here because they are really short, but I also attached a file "error.log" if you prefer.

Error :
`
../../../tools/winegcc/winegcc -o adsldp_test-stripped.exe -B../../../tools/winebuild -b i686-w64-mingw32 \
  --lib-suffix=.cross.a -s -Wb,-F,adsldp_test.exe -mno-cygwin sysinfo.cross.o testlist.cross.o \
  ../../../dlls/ole32/libole32.cross.a ../../../dlls/oleaut32/liboleaut32.cross.a \
  ../../../dlls/secur32/libsecur32.cross.a ../../../dlls/advapi32/libadvapi32.cross.a \
  ../../../dlls/uuid/libuuid.cross.a 
/usr/lib/gcc/i686-w64-mingw32/8.2.0/../../../../i686-w64-mingw32/bin/ld: cannot find -lgcc
/usr/lib/gcc/i686-w64-mingw32/8.2.0/../../../../i686-w64-mingw32/bin/ld: cannot find -lgcc_eh
/usr/lib/gcc/i686-w64-mingw32/8.2.0/../../../../i686-w64-mingw32/bin/ld: cannot find -lgcc
/usr/lib/gcc/i686-w64-mingw32/8.2.0/../../../../i686-w64-mingw32/bin/ld: cannot find -lgcc_eh
collect2: error: ld returned 1 exit status
winegcc: i686-w64-mingw32-gcc failed
`
[error.log](https://github.com/M-Reimer/wine-lol/files/3244780/error.log)

**Comment by M-Reimer** [comment]
Is this Manjaro or Arch? Check if your glibc is really up to date.

**Comment by M-Reimer** [comment]
Maybe that's the problem:
https://stackoverflow.com/questions/22157391/how-to-deal-with-linker-error-error-cannot-find-lgcc

**Comment by M-Reimer** [comment]
Try "pacman -S multilib-devel" and install the whole group.
Just guesswork but this is one of the "base groups" you should have for development.
If you haven't done already, also run "pacman -S base-devel"

**Comment by sinxn** [comment]
First, I use Archlinux.
glibc, gcc-multilib, and all the packages of multilib-devel and base-devel were already installed. I reinstalled them just to be sure, and also updated all my packages ("pacman -Syu") and rebooted after that.
But I still get exactly the same error. I have no idea of what to try.

**Comment by sinxn** [comment]
Oh i just managed to get a part of the error (only "missing -lgcc_eh") by chance by trying to cross compile with mingw a very little program which includes nearly only winsock2.h (the windows C library for sockets).
I don't know how but this info may be helpful I hope.

**Comment by M-Reimer** [comment]
This doesn't help me. I'm no "Wine compilation professional" :stuck_out_tongue: 
"Something" has to be "special" about your setup.
The "reduced" compile logs don't help either. Can you capture the full makepkg run and attach this here?
It works for several other users and now it even works with "yay" (AUR helper) but I really don't know why you have these compile errors.
Can you think of any specialities in your setup? Some kind of special kernel? Some special security settings? Maybe some special settings in /etc/makepkg.conf? Maybe it would help to reset "makepkg.conf" to the distribution standard.

**Comment by FrischerHering** [comment]
Since you cannot build the patched Wine for this lol fix, are you able to build default Wine as described here https://wiki.winehq.org/Building_Wine ?

**Comment by sinxn** [comment]
> Since you cannot build the patched Wine for this lol fix, are you able to build default Wine as described here https://wiki.winehq.org/Building_Wine ?

Oh well I just tried and got exactly the same error, I guess my issue has no place here anymore since it's not related to wine-lol.
Just in case I attach the full logs : [log.txt](https://github.com/M-Reimer/wine-lol/files/3253488/log.txt)
(Note that my username on this computer is "arch", it may be a bit confusing when reading)

Also, I have the official kernel and never modifier my makepkg.conf. I think there are some mingw-things missing but I can't figure out which ones. I'm going to try some things and we will see.

**Comment by sinxn** [comment]
Hey I'm not sure because I just reinstalled all my mingw-things, but I think I only had mingw-w64-gcc-base and not the full mingw-w64-gcc...
So I installed the second one (a precompiled version because compilation is loooooooooong), and classic wine seems to build well (it is not finished but has been running for 10 minutes, and my crash always happened in less than 5 minutes).
I will also try on wine-lol after and give news in some hours or tomorrow.

**Comment by sinxn** [comment]
Well I successfully built wine (the original wine). So I think I only had mingw-w64-gcc-base installed and not the full version, hum...
I am currently building wine-lol and I will post something and close this issue if it works, in some hours.

**Comment by sinxn** [comment]
Good news : wine-lol was correctly built !
So it was not linked to the patch for lol, I close the issue.
But I wonder why wine compilation needs a cross compiler toolchain...
