### ISSUE TITLE
PBE doesn't start when trying to play TFT.

### ISSUE THREAD

**Issue by EdithDehoyos** [M-Reimer/wine-lol#122]

**Comment by EdithDehoyos** [comment]
![image](https://github.com/M-Reimer/wine-lol/assets/109493974/a17ac1f7-74d5-43e1-8424-afaa911a1fa1)

These are the coredumps in my journal

**Comment by M-Reimer** [comment]
Did you use wine-lol-bin? If not, then please try if the problem exists there, too.

**Comment by EdithDehoyos** [comment]
> Did you use wine-lol-bin? If not, then please try if the problem exists there, too.

Yep, same issue. This time I started the league process in a terminal to see what messages it spits out. 

![image](https://github.com/M-Reimer/wine-lol/assets/109493974/fa6f92c4-2b1b-48de-9cd7-eec108881cf9)

**Comment by M-Reimer** [comment]
This means that this is a general "wine-ge-custom" issue. GloriousEggroll seems to prefer Discord for support. You can find the discord invite link here: https://github.com/GloriousEggroll/wine-ge-custom

**Comment by EdithDehoyos** [comment]
> This means that this is a general "wine-ge-custom" issue. GloriousEggroll seems to prefer Discord for support. You can find the discord invite link here: https://github.com/GloriousEggroll/wine-ge-custom

that's a shame, discord isn't a great place to make bug reports but what can you do.

I've done some research, apparently patch 13.22 is bugged, and the crashing happens not just for linux users. Hopefully Riot fixes this soon.
