### ISSUE TITLE
Arch AUR package installs forever

### ISSUE THREAD

**Issue by CyanideData2** [M-Reimer/wine-lol#123]
When manually installing the AUR package, the installing process never ends. There seems to be a looped pattern in the logs that the terminal display but it is too much text for me to post here. I am kind of new to Arch Linux so it may be a problem of my system rather than the wine package itself

**Comment by M-Reimer** [comment]
You don't "install an AUR package" but you build using a PKGBUILD file and then install the resulting package.

Which step "takes forever" for you? Building or installing? The build process can take really long depending on how powerful your system is. Around one hour build time is not uncommon.
