### ISSUE TITLE
Estou tendo erro no  "_FORTIFY_SOURCE" 

### ISSUE THREAD

**Issue by Raijoia** [M-Reimer/wine-lol#124]
Quando tento instalar, dá esse erro
`: aviso: "_FORTIFY_SOURCE" redefinido
: nota: este é o local da definição anterior`

**Comment by M-Reimer** [comment]
Please English only. I cannot read that!

**Comment by M-Reimer** [comment]
I hope this is resolved with the upcoming wine update.
