### ISSUE TITLE
Can't write chat messages

### ISSUE THREAD

**Issue by DRL-28** [M-Reimer/wine-lol#13]
I cannot write in the game in my own language (Russian). When typing a message just nothing happens.

**Comment by M-Reimer** [comment]
I don't think that this is related to the wine build. Did it work with regular wine?

**Comment by DRL-28** [comment]
Yes, with any other version of wine I could write messages in Russian

**Comment by FrischerHering** [comment]
Is your client set to Russian? I remember that I could not create a Russian summoner name on Russian servers, because my client was set to English locally. Maybe reinstall League. I don't think that this is the fault of this Wine build.

**Comment by DRL-28** [comment]
No, if I now launch the same client through my system wine, I can write a message in Russian

**Comment by DRL-28** [comment]
If I collect wine from the source myself, I can also write messages.
If I collect wine with your script, then I cannot write messages.

**Comment by FrischerHering** [comment]
Is this an issue with wine or with the patched glibc then? Did you try building default wine against the patched glibc?

**Comment by DRL-28** [comment]
Perhaps this is a problem in glibc, I do not argue.
I did not try to collect wine from the source with the glibc. I do not understand how to do it.

**Comment by FrischerHering** [comment]
I cannot test it right now, but I think this should do the trick, just to verify:
After cloning this repository, edit the `PKGBUILD` file and comment out (or remove) lines 134-137.
```
pushd "$srcdir/$pkgname"
  patch -p1 -i "$srcdir/wine-lol–poc1-wine.diff"
  patch -p1 -i "$srcdir/wine-lol-patch-stub.diff"
popd
```
Then running `makepkg` should build wine with patched glibc, but without lol related fixes.
Most certainly, you will get the same issue again. I would assume there is a misconfiguration when building either glibc or wine, which breaks the localization stuff... In my opinion reading up on language related issues when building glibc or wine would be the best bet. Or waiting for an official adaptation of a league fix in wine.

**Comment by DRL-28** [comment]
![wine-lol](https://user-images.githubusercontent.com/33255217/58886872-911f6300-871f-11e9-9ee4-1b7c76296b40.jpg)
![wine-system](https://user-images.githubusercontent.com/33255217/58886886-9381bd00-871f-11e9-9e1f-b28af8a89fe6.jpg)

I attached 2 screenshots.
1 this is wine-lol from aur
2 is the usual wine from the archlinux repository.

**Comment by M-Reimer** [comment]
I have an idea why this could be caused by wine-lol-glibc but I have to prepare a testcase first.
Stay tuned. I'll post again later this evening.

**Comment by M-Reimer** [comment]
Possible temporary fix:
# rm -r /opt/wine-lol/lib32/locale
# ln -s /usr/lib/locale /opt/wine-lol/lib32/locale

Please tell me if this works.

**Comment by DRL-28** [comment]
I confirm that after executing these commands I can write messages in Russian. Also winecfg began to be displayed completely in Russian. Fine! Thank!

**Comment by DRL-28** [comment]
Why is this a temporary solution?
Is there another way to fix this problem?

**Comment by M-Reimer** [comment]
No, but I'll have to fix this in the PKGBUILD so no manual fixing is needed.

**Comment by DRL-28** [comment]
Got it.
Thank you very much.
Great job. =)

**Comment by DRL-28** [comment]
Can i close this problem?

**Comment by M-Reimer** [comment]
I've moved it over to wine-lol-glibc
I'll fix this on Friday or Saturday.
