### ISSUE TITLE
No gtk/gtk.h found: Cannot build

### ISSUE THREAD

**Issue by ItsAdhire** [M-Reimer/wine-lol#14]
Sorry in advance because I'm very new to github and linux. I've been trying makepkg and I keep getting this error.

`gcc -m32 -c -o gtk-button.o ../../../wine-lol/dlls/uxtheme/gtk-button.c -I. -I../../../wine-lol/dlls/uxtheme \
  -I../../include -I../../../wine-lol/include -D__WINESRC__ -D_REENTRANT -fno-PIC -Wall -pipe \
  -fno-strict-aliasing -Wdeclaration-after-statement -Wempty-body -Wignored-qualifiers \
  -Wno-packed-not-aligned -Wshift-overflow=2 -Wstrict-prototypes -Wtype-limits \
  -Wunused-but-set-parameter -Wvla -Wwrite-strings -Wpointer-arith -Wlogical-op \
  -fno-omit-frame-pointer -D_FORTIFY_SOURCE=2 -m32 -march=x86-64 -mtune=generic -O2 -pipe  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0
In file included from ../../../wine-lol/dlls/uxtheme/gtk-button.c:25:
../../../wine-lol/dlls/uxtheme/uxthemegtk.h:28:10: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:240: gtk-button.o] Error 1
make[1]: Leaving directory '/home/adhire/Programs/wine-lol/src/wine-lol-32-build/dlls/uxtheme'
make: *** [Makefile:8879: dlls/uxtheme] Error 2
==> ERROR: A failure occurred in build().
`

Am I missing something or is there something I'm doing wrong?

**Comment by M-Reimer** [comment]
Never seen that error. Sorry.
You use regular "makepkg"?
Try "makepkg -s" please. This would try to download missing dependencies, first.

**Comment by ItsAdhire** [comment]
I used makepkg -sri

**Comment by ItsAdhire** [comment]
I tried to re install wine-lol and it seems I have got a new error. `checking for -lfreetype... not found

configure: error: FreeType 32-bit development files not found. Fonts will not be built.

Use the --without-freetype option if you really want this.
==> ERROR: A failure occurred in build().
    Aborting...
`

could this be causing my previous error?

**Comment by M-Reimer** [comment]
Seems like you miss some 32 bit libraries.
But "makepkg" should throw an error if something is missing...
The "wine-lol" PKGBUILD has "lib32-freetype2" listed as dependency so it should be there...

**Comment by ItsAdhire** [comment]
I figured out the issue, it has nothing to do with wine-lol. I accidently screwed up something with a pacman file on my system. I fixed it and it works now. Thanks for the help.
