### ISSUE TITLE
Stuck on client startup

### ISSUE THREAD

**Issue by Zooruv** [M-Reimer/wine-lol#15]
Hey, I'm currently trying to setup league with wine-lol and and i keep getting stuck on the client startup. I used the draft install script in the lutris page. I have also tried not using lutris but i ran into the same problem. I'm using Artix Linux x64 (basically identical to Arch). Help would be much appreciated, thanks for your time.

![](https://i.imgur.com/S9t1niV.png)

[Lutris log](https://pastebin.com/T3FVj8Sv)

EDIT: I also used yay to build wine-lol and wine-lol-glibc without any problems.

**Comment by M-Reimer** [comment]
It would be better if you address this problem to the "League Of Linux" subreddit.
https://www.reddit.com/r/leagueoflinux/
I'm no wine professional and this log file doesn't tell me anything.
As you were able to compile without errors, I think the PKGBUILD itself is not your issue and your build is fine.
