### ISSUE TITLE
README.md or install instructions ?

### ISSUE THREAD

**Issue by haliliceylan** [M-Reimer/wine-lol#16]
Hey Guys,

How can i install this library. I did not have experience about that makepkg or another command.
I look at some issues and i try to this command but i am getting this error.
![image](https://user-images.githubusercontent.com/33789758/59547518-f574ca80-8f48-11e9-938b-4cb7034ef7ae.png)
Please somebody give me install instructions :cry: 

I am using Manjaro Stable (Linux halil-pc 4.19.49-1-MANJARO #1 SMP PREEMPT Sun Jun 9 20:24:20 UTC 2019 x86_64 GNU/Linux)
All updates are installed.

**Comment by M-Reimer** [comment]
A short google search brings:
https://www.reddit.com/r/linuxmasterrace/comments/8pag45/cleanbuild/
Maybe this helps.
I've never used "yay", too but I think you can just answer with "A" for "All" here.

**Comment by haliliceylan** [comment]
I cloned both repository. and Run the makepkg -si. I am waiting. If finished succesfully ı will send pr for readme.md

**Comment by M-Reimer** [comment]
I don't think that this is the way for the beginner. Helpers like yay can help a lot here

**Comment by haliliceylan** [comment]
I've looked at other issues. The author is recommending use makepkg instead of yay. (see also on last replies: #3)

**Comment by M-Reimer** [comment]
The reason for not working with yay is fixed

**Comment by haliliceylan** [comment]
okey sir. I abort the install and i am trying re-install. Thanks for your helping.

**Comment by M-Reimer** [comment]
All you have to do is to "request" wine-lol via yay. The required winw-lol-glibc is auto-resolved by yay.

**Comment by haliliceylan** [comment]
I runned these commands. 
```
yay -s wine-lol-glibc
yay -s wine-lol
```

**Comment by haliliceylan** [comment]
is this will take 1 year ? still compiling...

**Comment by M-Reimer** [comment]
https://wiki.archlinux.org/index.php/Makepkg#Improving_compile_times

**Comment by haliliceylan** [comment]
Hey, i have error with this wine build.Should i open new issue ?
![image](https://user-images.githubusercontent.com/33789758/59551242-31c31d80-8f7f-11e9-9779-f49c3862bc57.png)

**Comment by haliliceylan** [comment]
wine shared libraries;
![image](https://user-images.githubusercontent.com/33789758/59551250-515a4600-8f7f-11e9-860b-82ee09b9d1f1.png)
wine graphic option;
![image](https://user-images.githubusercontent.com/33789758/59551254-620abc00-8f7f-11e9-95b2-5a8826a3a2d8.png)

**Comment by haliliceylan** [comment]
GameError Log.
```
{

    "access_addr": 0,

    "access_type": "Read",

    "cpu_type": 586,

    "exception_type": "ACCESS_VIOLATION",

    "free_page_file_bytes": 20343955456,

    "free_physical_mem_bytes": 4275490816,

    "free_virtual_mem_bytes": 4294770687,

    "game_version": "9.12.278.2588",

    "mem_load_pct": 30,

    "module_name": "League of Legends",

    "num_cpus": 4,

    "total_page_file_bytes": 22224359424,

    "total_physical_mem_bytes": 6118670336,

    "total_virtual_mem_bytes": 4294836223

}
```

**Comment by M-Reimer** [comment]
Even if you open a new issue, I won't be able to help. For everything beyond compiling this subreddit is the better address:
https://www.reddit.com/r/leagueoflinux/

**Comment by haliliceylan** [comment]
Thank you for everything. I'm sorry if I disturbed you.

**Comment by M-Reimer** [comment]
You did not disturb me.
Nice to know that you were successful with yay.
But this error messages don't tell me anything.
I've never seen them.
I'm no LoL developer and no wine professional.
So the best way to get help would be to ask in this subreddit. Maybe someone has already seen such errors and can tell you how he fixed the problem.
