### ISSUE TITLE
Create a repository

### ISSUE THREAD

**Issue by baronleonardo** [M-Reimer/wine-lol#17]
could you please use <https://build.opensuse.org> to create a repository for this package ?

**Comment by M-Reimer** [comment]
This would only help me if it would work somewhat "automatically".
But unfortunately they have some bugs with handling of PKGBUILD build scripts.

https://github.com/openSUSE/obs-service-download_files/issues/25
https://github.com/openSUSE/obs-service-download_files/pull/13

And as the service targets OpenSUSE primarily, fixing PKGBUILD related stuff doesn't seem to be top priority.

Without these fixed, I would have to do too much handling on my side which would make it faster to build on my local machine than on theirs.

**Comment by M-Reimer** [comment]
I've prepared a build configuration for repo-make to build the repository:
https://github.com/M-Reimer/wine-lol-repo
And the result is uploaded to here:
https://m-reimer.de/wine-lol/
