### ISSUE TITLE
Plan on keeping up with wine?

### ISSUE THREAD

**Issue by HiiroSakaki** [M-Reimer/wine-lol#18]
Hello,

Do you plan on keeping this up to date along wine?
Wine is ""already"" at 4.11, but I don't know how tough
it is to follow the train

Cheers!

**Comment by M-Reimer** [comment]
I'll not update with priority. That's one nice thing when the LoL wine version is separated. No need to patch as long as LoL works.

For everything else wine-staging is updated by the Arch developers.

**Comment by M-Reimer** [comment]
Updated to 4.12.1
The "plan" is to only update if it is really needed. This wine version has to run one program only and as long as there are no problems, no update is needed.
