### ISSUE TITLE
Configure error aborts compilation

### ISSUE THREAD

**Issue by FrischerHering** [M-Reimer/wine-lol#2]
When building Wine-64:
```
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
==> ERROR: A failure occurred in build().
    Aborting...
```
[config.log](https://github.com/M-Reimer/wine-lol/files/3193042/config.log)

**Comment by M-Reimer** [comment]
You have to get sure that you definitively run your system on exactly the same glibc version as you want to build as wine-lol-glibc. If for some reason you want to keep an older version, then also downgrade wine-lol-glibc to exactly this version.
The way, I did the building against the patched glibc doesn't allow a version difference!

**Comment by FrischerHering** [comment]
Both my system glibc and the wine-lol-glibc run 2.29-1

**Comment by M-Reimer** [comment]
Do you build manually? Please don't use any helper tools besides makepkg.

**Comment by FrischerHering** [comment]
I built wine-lol-glibc with yay as other users suggested and wine-lol with makepkg. I reinstalled both glibc and lib32-glibc prior to this. All glibc related packages are with 2.29-1.

**Comment by FrischerHering** [comment]
Building wine-lol-glibc with makepkg only still results in mentioned configure error when building wine-lol...

**Comment by M-Reimer** [comment]
I can't reproduce this error and I also can't really read something useful from your log file.
Maybe someone else has an idea.
I still hope for a fix that doesn't need glibc modifications. Would make things so much easier...

**Comment by Black88ad** [comment]
remove lines:
     --enable-win64 \
resolve problem

**Comment by ivil** [comment]
I've got another problem 
==> ERROR: A failure occurred in prepare().
    Aborting...
Error making: wine-lol-glibc

Manjaro

**Comment by Black88ad** [comment]
did you remove src folder before start again compile ?

**Comment by ivil** [comment]
Yup.
And i forget to mention i used yay, to install package.

**Comment by ivil** [comment]
Okay. i was missing base-devel ;-;

**Comment by FrischerHering** [comment]
So I think I just borked up my system glibc from fiddling around with the fix yesterday, reinstalling system files solved the issue. Issue closed. Latest comments are unrelated.

**Comment by M-Reimer** [comment]
Thanks for the feedback.
That's exactly the reason why I decided to do all this with a separate glibc.
Better to have problems with wine/League than with every single binary on my system.
