### ISSUE TITLE
League version 9.10

### ISSUE THREAD

**Issue by jorpilo** [M-Reimer/wine-lol#23]
League breaks on version 9.10

https://bugs.winehq.org/show_bug.cgi?id=47198

It has been fix using the following patch of comment 39 and disabling vsyscall32 comment 40.

https://bugs.winehq.org/attachment.cgi?id=64507&action=diff

The game with the patch works without the need to patch glib. I would be interesting to update the build script to include this patch.

**Comment by jorpilo** [comment]
I created a small repo with the PKGBUILD with wine from git, stage and the patches to run the game.

https://github.com/jorpilo/wine-lol

**Comment by jorpilo** [comment]
I created a small git with wine + staging + lol patches

https://github.com/jorpilo/wine-staging-lol

**Comment by M-Reimer** [comment]
As far as I know there is no problem at all with the current state which is on AUR already.
The solution, used in this repository here and on AUR does not require to disable vsyscall32.
There is also a binary repository that you can use:
https://m-reimer.de/wine-lol/
