### ISSUE TITLE
Remove the mesa-libgl dependency

### ISSUE THREAD

**Issue by gusix** [M-Reimer/wine-lol#24]
Some versions of mesa does not provide mesa-libgl, mesa-aco-git in my case, I removed the dependency manually and it builds and runs just fine (mesa is the only actual provider for mesa-libgl and is already a dependency anyway)

**Comment by M-Reimer** [comment]
This dependency is also in the "official" wine PKGBUILD's.
I haven't had a deeper look into this, but "wine-git does not have it" is no valid reason for dropping it.
Will have to investigate a bit further if I find the time.
Maybe it's also the other "mesa PKGBUILD's" which are wrong here. Maybe they should add "mesa-libgl" to the "provides" list?

**Comment by gusix** [comment]
I just asked on the other side, you may be right, but changing this pkgbuild seemed quicker than every single mesa package on the AUR.
