### ISSUE TITLE
error wine-lol version 4.17-1

### ISSUE THREAD

**Issue by aleex5** [M-Reimer/wine-lol#28]
freetype is installed, but still that error comes out
i'm using manjaro linux

checking for -lfreetype... not found
configure: error: FreeType 32-bit development files not found. Fonts will not be built.

**Comment by M-Reimer** [comment]
You have to update wine-lol-glibc

**Comment by aleex5** [comment]
it was the first thing that was updated

I will try to uninstall them and reinstall

**Comment by M-Reimer** [comment]
OK. Didn't read that you are on Manjaro. There it may actually be a problem to upgrade wine-lol-glibc. You may have to wait for Manjaro to get glibc 2.30, first

**Comment by aleex5** [comment]
I guess I'll have to wait for Manjaro to update, thankfully I still have the previous version of wine-lol

**Comment by M-Reimer** [comment]
You should be able to build the updated release if you keep the old wine-lol-glibc.
It's just the problem that the gcc-libs and the glibc used for linking have to match.
I had to update wine-lol-glibc as otherwise it is impossible to build on Arch.

**Comment by jukefr** [comment]
You can also switch to Manjaro's unstable branch, which makes you use arch's default repositories more or less. (So you get glibc2.30)

**Comment by M-Reimer** [comment]
As far as I know Manjaro now also has glibc 2.30, so this issue should be fixed.
