### ISSUE TITLE
Alt Key does not work with the new version

### ISSUE THREAD

**Issue by InfernalConcept** [M-Reimer/wine-lol#29]
Since the update / compilation of the new version from 2019-10-06 the Alt keyis no longer recognized. So I can't use "Quick Allert Pings" (Alt +MB1) in Lol.

**Comment by M-Reimer** [comment]
Please add this change and try again

https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/wine-staging&id=1c902ca0ad671ea09b5ebf78dc9724014f1d770a
