### ISSUE TITLE
League starts fine, keyboard does not work...

### ISSUE THREAD

**Issue by yooouuri** [M-Reimer/wine-lol#40]
> The client and game are working fine. When I get in the game, my keyboard does not work for some reason.
> 
> Weird enough when I alt+tab back into the game, the keyboard is working but I cant navigate with the mouse....
> 
> Using syscall_check.sh (using Lutris) and ofcourse your wine-lol.
> 
> Can you tell me what logs do you want? So I can attach them.
> 
> Having an AMD RX570. Running Arch

When I checked D9VK it worked for some reason.

I will close the issue.

**Comment by JJK96** [comment]
I have the same issue, how did you fix it?

**Comment by yooouuri** [comment]
I guess it worked for once, but it didnt worked the second time....

**Comment by M-Reimer** [comment]
You have to discuss this on Reddit.
No wine developers here.
https://www.reddit.com/r/leagueoflinux/

**Comment by yooouuri** [comment]
@JJK96 https://www.reddit.com/r/leagueoflinux/comments/e805c5/league_starts_fine_keyboard_does_not_work/ created reddit topic
