### ISSUE TITLE
ERROR: Remote key not fetched correctly from keyserver.

### ISSUE THREAD

**Issue by yooouuri** [M-Reimer/wine-lol#41]
```
dreamworld% sudo pacman-key --recv-key D5E3DF45D8312635
[sudo] password for youri: 
gpg: keyserver receive failed: Permission denied
==> ERROR: Remote key not fetched correctly from keyserver.
```

**Comment by M-Reimer** [comment]
Maybe the same as this issue:
https://github.com/Jguer/yay/issues/656

Check

    /etc/pacman.d/gnupg/gpg.conf

What is your configured "keyserver"?

**Comment by M-Reimer** [comment]
No more feedback. Closing.

**Comment by Zush18** [comment]
Same problem.
I solve it by adding a keyserevr in `/etc/pacman.d/gnupg/gpg.conf`

`keyserver hkp://pgp.mit.edu:11371`

My distro didn't have it by default

**Comment by ratzakogl** [comment]
The solution provided by @Zush18 did not work on my system. (pacman-key (pacman) 5.2.2)
I tried querying `pgp.mit.edu` manually and it looks like they are having problems at the moment with 2 out of my 3 queries leading to a timeout. 

What finally did the trick for me was specifying another keyserver with the `--keyserver` option:
`sudo pacman-key --recv-key 0xD5E3DF45D8312635 --keyserver hkps.pool.sks-keyservers.net`

Signing the key once it was fetched worked as expected.
`sudo pacman-key --lsign-key D5E3DF45D8312635`

**Comment by M-Reimer** [comment]
For some reason the quality of keyservers seems to be unreliable. I have similar problems with another project where I had to hardcode a keyserver for reliability. I thought that the keyservers exchange keys between each other but I may be wrong here...
