### ISSUE TITLE
no conatct list since patch 10.x

### ISSUE THREAD

**Issue by InfernalConcept** [M-Reimer/wine-lol#43]
No contacts or groups are displayed. The contacts box is an empty black box on the right side of the client.

**Comment by M-Reimer** [comment]
I have not used LoL for quite some time but for the majority it seems to still work.
Anyway this GIT repo is just for the PKGBUILD itself. There are no Wine developers here!
So please forward your request to:
https://www.reddit.com/r/leagueoflinux/
