### ISSUE TITLE
Slow client startup

### ISSUE THREAD

**Issue by leaty** [M-Reimer/wine-lol#45]
Not a huge issue, but I want to leave this here in case others are having the same experience.

With the new client meant for their new catalog of games, things have gotten quite slow. After logging in, it takes almost 2 minutes for the actual League client to open. It seems that it's waiting for something that isn't working, unfortunately with a rather long timeout.

**Comment by JJK96** [comment]
I experience the same issue.

Have you reported this upstream? 
This repo is just for the PKGBUILD itself. There are no Wine developers here.

**Comment by leaty** [comment]
No, I've not. Yes I know, I guess I'm too used to github.
