### ISSUE TITLE
Unable to build due to Freetype

### ISSUE THREAD

**Issue by Roboron3042** [M-Reimer/wine-lol#46]
When building on Arch Linux I get the following error:

checking for -lfreetype... not found
configure: error: FreeType 32-bit development files not found. Fonts will not be built.
Use the --without-freetype option if you really want this.

Of course, both Freetype and Freetype 32-bit libraries are installed (it is a dependency of wine-lol, after all). What's happening?

**Comment by M-Reimer** [comment]
Always build and install wine-lol-glibc first. And always be sure wine-lol-glibc is the same version as the system glibc when building. For running the versions may differ but not for compiling.

**Comment by Roboron3042** [comment]
> Always build and install wine-lol-glibc first.

I'll have to tattoo me this in my hand.
