### ISSUE TITLE
missing MSVCRT

### ISSUE THREAD

**Issue by nicolube** [M-Reimer/wine-lol#49]
Is there a way to add the libery MSVCRT?
With "WINEPREFIX=~/lol-wine/ winetricks" does not seems to do it...
I want to add this because it seems that it needs it to load the frinds list.

**Comment by M-Reimer** [comment]
This is exactly the way to do it. Sure you got the path to your WINEPREFIX right?

**Comment by nicolube** [comment]
Ok never mind,
I just started the game and it repaired it self and i have a different login screen now...
Bute the frinds are working now.
But it spawms ... in the terminal.
`010d:fixme:msvcrt:MSVCRT__stdio_common_vsnprintf_s options 24 not handled
`
