### ISSUE TITLE
Alt+F4 doesn't work.

### ISSUE THREAD

**Issue by raspin0** [M-Reimer/wine-lol#52]
Is there a way to fix alt+f4? Lutris lol have this functionality, but it requires you to set abi.vsyscalls.

**Comment by M-Reimer** [comment]
> Is there a way to fix alt+f4?

I don't know.

> Lutris lol have this functionality, but it requires you to set abi.vsyscalls.

I also don't know how they do it if they actually do it. TBH I never tried to hit "Alt + F4" inside LoL. If I need to close the game, I use my mouse to do it.

Maybe this is one of the cases that should be better discussed here:
https://www.reddit.com/r/leagueoflinux/

If someone points me to the patch that is needed, I can add it and test if this has any influence on "Alt + F4". But I won't do this work on my own.

**Comment by vesterlay** [comment]
Thanks for the response, I will try to make a post there. It's not like I must have this functionality, but old habits die hard..

**Comment by raspin0** [comment]
As Riot has changed alt+f4 behavior, I don't think this issue is as relevant right now. Closing..
