### ISSUE TITLE
Wien 5.11 includes a bunch of League fixes

### ISSUE THREAD

**Issue by ilyazzz** [M-Reimer/wine-lol#54]
I know that this repository doesn't get updated simply because there's a new wine version, but 5.11 includes some fixes which may remove the need for some of the patches applied:

>   45571  League of Legends 8.12+ fails to start a game (anticheat engine, hooking of NtCreateThread/Ex)
  45572  League of Legends 8.12+ fails to start a game (anticheat engine, hooking of NtContinue)
  45667  League of Legends 8.15+ fails due to missing implementation of NtQueryVirtualMemory(MemoryWorkingSetExInformation)

The regressions from 5.7 seem to be fixed also.

**Comment by M-Reimer** [comment]
We are down to just one patch that will still be needed with 5.11 anyway.

The fixes in your list are, as far as I know, only fixes for regressions. Stuff may be fixed "in a better way" now, but LoL works for me with version 5.6, so what?

"Seem to be fixed also" means that you did not test if this wine version works at all.
And I don't have the time to test this either.
