### ISSUE TITLE
error : glibc 2.32 not found

### ISSUE THREAD

**Issue by arav12ind** [M-Reimer/wine-lol#57]
when i tried running wine-lol, i get this error every time.
I tried reinstalling wine-lol, wine-lol-glibc, glibc ,lib32-glibc.
wine: failed to initialize: /opt/wine-lol/lib32/libc.so.6: version `GLIBC_2.32' not found (required by /opt/wine-lol/lib32/wine/ntdll.dll.so)

**Comment by M-Reimer** [comment]
Fixed by updating wine-lol-glibc
