### ISSUE TITLE
AUR: Invalid sha512 and failure to apply patch

### ISSUE THREAD

**Issue by sgleizes** [M-Reimer/wine-lol#59]
First of all thanks for your work in favor of Linux gaming.

I just tried building wine-lol from the AUR and got a sha512 mismatch for the wine patch `wine-lol-bug-47198-fix.patch`. I've seen you recently did a rename so I updated the PKGBUILD. But then the second hunk of the patch failed to apply on wine 5.6:
```
patching file dlls/ntdll/thread.c
Hunk #1 succeeded at 206 with fuzz 2 (offset -20 lines).
Hunk #2 FAILED at 501.
1 out of 2 hunks FAILED -- saving rejects to file dlls/ntdll/thread.c.rej
==> ERROR: A failure occurred in prepare().
```

It seems indeed that the patch is invalid for this version of wine.

I'm running Arch with the latest updates, no AUR helper.

**Comment by Dezyh** [comment]
Also got this exact issue both with and without an AUR helper.

**Comment by M-Reimer** [comment]
Patch applies. Checksum is correct. Trying to build now but so far no issues whatsoever.

I guess you did not remove "src" and "pkg" in the PKGBUILD source directory. You **always** have to do this before recompiling!

**Comment by M-Reimer** [comment]
Compiled through without any issues. So works for me.

Can someone please test with the "src" and "pkg" directories gone?

**Comment by sgleizes** [comment]
I was building it for the first time, so I originally had no untracked files in the source directory.
Just tried again, removing everything and I can confirm that it still happens.

Steps to reproduce:
```
git clone https://aur.archlinux.org/wine-lol && cd wine-lol
makepkg -sirc
```
Right after the clone, running `sha512sum wine-lol-bug-47198-fix.patch` gives:
`a6f8079da8727cc5b23e9895b41e2010b00e3268a9152aaaf03ab801f1b2e1d6a3e5860de69a0a8f31e983f585a14a42fb3d9b6e68aacc4749ee91c0fdb2794f`
Whereas the PKGBUILD has:
`a17db33ba5d6114bd71d1b013adc8e5ca0c3cedf856301cba59f95dadf643d2ee0e5a2d7abb2daedd5ed7c45cdbe93c78527f4d962bedc54776bb21cfc7e8b0b`

**Comment by sgleizes** [comment]
If that can help about the patch correctness, it seems that the downloaded version of wine (5.6) has the following code in thread.c in `thread_init` (second hunk):
```
 441   │     /* initialize user_shared_data */
 442   │     __wine_user_shared_data();
 443   │     fill_cpu_info();
 444   │
 445   │     virtual_get_system_info( &sbi );
 446   │     user_shared_data->NumberOfPhysicalPages = sbi.MmNumberOfPhysicalPages;
 447   │
 448   │     return teb;
 449   │ } 
```
Where the failing patch hunk is:
```
@@ -430,6 +501,11 @@ TEB *thread_init(void)
     unix_funcs->dbg_init();
     unix_funcs->get_paths( &build_dir, &data_dir, &config_dir );
     fill_cpu_info();
+
+#ifdef __i386__
+   seccomp_init();
+#endif
+
     return teb;
 }
```

**Comment by M-Reimer** [comment]
Try again. Seems like something slipped in with my now 3 different branches.

**Comment by sgleizes** [comment]
It's building now. Thank you!
