### ISSUE TITLE
How to install in non-Arch distributions?

### ISSUE THREAD

**Issue by Derpford** [M-Reimer/wine-lol#6]
There appears to be an AUR package for this, but there's no build instructions for non-Arch distros. I'm on OpenSUSE and would like to get back to playing. How do I build this fix?

**Comment by M-Reimer** [comment]
I can't tell you.
This repository is just for the Arch PKGBUILD.
And if you have a look at the PKGBUILD file you'll see that they are just "special shellscripts" and so pretty easy to read and understand.
It should be possible to port the build process to whatever "OpenSuSE" uses.
For further questions, I can recommend this Subreddit:
https://www.reddit.com/r/leagueoflinux/
