### ISSUE TITLE
Update https://m-reimer.de/wine-lol/$arch

### ISSUE THREAD

**Issue by ISOUBAASSTONED** [M-Reimer/wine-lol#61]
Hey, I use your wine-lol and wine-lol-glibc build of wine-staging. It seems you didn't update the binary in https://m-reimer.de/wine-lol/$arch. Would you please do so or should I rather compile from aur? I'm refering to the latest issue with wine-lol that got fixed on the 14th, but no update came when updating from your repo.

**Comment by M-Reimer** [comment]
This does fix only the building. If you have mingw installed then wine picked it up and built with it which causes a build error. So nothing was fixed which causes any changes with LoL.

**Comment by ISOUBAASSTONED** [comment]
Sorry About that, I was scrolling through r/leagueoflinux and found a few posts saying I should use the wine-lol package as a fix. Of course that was weird since i was already using it and still got the error. Thanks for clearing it up and love your work.
