### ISSUE TITLE
New way of launching client (without launcher)

### ISSUE THREAD

**Issue by JulianKowalczuk** [M-Reimer/wine-lol#62]
https://www.reddit.com/r/leagueoflinux/comments/j07yrg/starting_the_client_script/

**Comment by JulianKowalczuk** [comment]
@M-Reimer can You explain why did You mark this issue as invalid?
Above script works perfectly fine with Your wine-lol solution

**Comment by M-Reimer** [comment]
This repo is only about wine-lol, its dependencies and its compilation.

You are right that the script helps. I use it myself. But it is nothing that I can include in wine-lol.

So I keep this Issue for information as long as its valid but with the label "invalid" as this Issue can not be solved in or for wine-lol.

**Comment by JulianKowalczuk** [comment]
I don't like to see repos with open unresolved issues. If Your repo readme is not place for this information, where is it?
Maybe Your site? I understand that these scripts are not part of Your repo but...
Many users without experience may find Your repo, but not these scripts and finally at the end they will say "ok, lol is not working on linux, i go back to windows", but I hope that's not what we wish

**Comment by M-Reimer** [comment]
There already is way more information on the README than I initially wanted to have there. If I add even more, noone will read anything from there.

This repo is only about wine-lol itself and not about installing LoL. I also don't have step-by-step installation instructions in the README document. Users have to find this information somewhere else.

There are different projects for installing LoL on Linux. You can use Lutris to install and then switch to wine-lol after doing so. There is https://aur.archlinux.org/packages/leagueoflegends-git/ on AUR and last but not least I also have a small helper script here:
https://github.com/M-Reimer/leagueoflegends-linux

But I think to provide some basic info both, README and wine-lol homepage should get a short link list to common helpers and the leagueoflinux Reddit.

**Comment by M-Reimer** [comment]
My install helper was updated a while ago and the instructions on the leagueoflinux subreddit cover this problem, too. So I think this one can be closed.
