### ISSUE TITLE
Con't download 0005-server-Broadcast-rawinput-message-if-request-flag-is.patch

### ISSUE THREAD

**Issue by WingDust** [M-Reimer/wine-lol#63]
Con't download https://raw.githubusercontent.com/wine-staging/wine-staging/8d4d0a840e6ce434483edd81acb3be90fd734e44/patches/user32-rawinput-mouse/0005-server-Broadcast-rawinput-message-if-request-flag-is.patch

Can tell me how manual install 
I can download `0005-server-Broadcast-rawinput-message-if-request-flag-is.patch` from web

**Comment by WingDust** [comment]
OS : Arch linux

**Comment by M-Reimer** [comment]
Please post the relevant part of the makepkg output.

I did a try just now and for me makepkg downloads this patch without any problems.

**Comment by M-Reimer** [comment]
No more feedback. Closing because it works for me.
