### ISSUE TITLE
configure failed

### ISSUE THREAD

**Issue by kyechou** [M-Reimer/wine-lol#65]
`../wine-lol/configure` failed, which seems to be some patching error. Here's a part of the log when pulling and building from the AUR package.

```
==> Starting build()...
  -> Building Wine-32...
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking for g++... g++
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking for cpp... cpp
checking for ld... ld
checking whether gcc -m32 works... yes
checking for the directory containing the Wine tools... 
checking for flex... flex
checking whether flex is recent enough... yes
checking for bison... bison
checking whether bison is recent enough... yes
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking whether ln -s works... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ldconfig... /sbin/ldconfig
checking for msgfmt... msgfmt
../wine-lol/configure: line 7543: syntax error near unexpected token `newline'
../wine-lol/configure: line 7543: `    '''
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by baptisterajaut** [comment]
Can confirm, have exactly the same issue

**Comment by td77** [comment]
Same for me using pacaur to build

**Comment by kyechou** [comment]
FYI, one can still install wine-lol from M-Reimer's binary repository (https://m-reimer.de/wine-lol/) if needed. I'm guessing there probably are some upstream changes that messed up the patching process.

**Comment by baptisterajaut** [comment]
> FYI, one can still install wine-lol from M-Reimer's binary repository (https://m-reimer.de/wine-lol/) if needed. I'm guessing there probably are some upstream changes that messed up the patching process.

Oh i was not aware of that ! At least now i can play (lutris method is broken for me)

**Comment by M-Reimer** [comment]
I can reproduce the problem but I won't be able to fix it. I have no clue why configure fails. I could not find which line in "configure.ac" causes the bad line in "configure" and I don't know which fix in later Wine versions fix this problem.

I can't put into words how much I HATE autoconf!

**Comment by baptisterajaut** [comment]
The lord has spoken.

I personally dont even understand the syntax error in the configure. Whats
wrong? The > '' < should not be here?

Le sam. 2 janv. 2021 à 15:10, Manuel Reimer <notifications@github.com> a
écrit :

**Comment by M-Reimer** [comment]
> The > '' < should not be here?

Maybe. But even if that's the case it is not really possible to know what would be right as "configure" is auto-generated from "configure.ac" with this shitty "autoconf" tool. Probably this was fixed in Wine at some point but I don't know where and we can't just place a more recent configure.ac into an older Wine.

**Comment by baptisterajaut** [comment]
The weird thing is that seems really new? I dont really understand the wine
source browser but it seems noone touched the configure file recently.
Maybe there was a zsh update that broke something?
Le sam. 2 janv. 2021 à 15:15, Manuel Reimer <notifications@github.com> a
écrit :

**Comment by M-Reimer** [comment]
Downgrading autoconf fixes the problem. With this information I continued to search and found:

https://www.winehq.org/pipermail/wine-devel/2020-October/176324.html

Not tested so far.

**Comment by kyechou** [comment]
> Downgrading autoconf fixes the problem. With this information I continued to search and found:
> 
> https://www.winehq.org/pipermail/wine-devel/2020-October/176324.html

I just tested this patch, and it works for me on my laptop.

**Comment by M-Reimer** [comment]
Updated here and on AUR. I did not push pkgrel as this fix is just for making it build again.

**Comment by baptisterajaut** [comment]
Amazing, thank you.
Do you happen to take any donation?
