### ISSUE TITLE
Release package

### ISSUE THREAD

**Issue by jpldcarvalho** [M-Reimer/wine-lol#7]
I cannot compile wine with my computer (out of curiosity, it's a Manjaro OS). I'm trying to debug and solve this problem, but everytime I test a new setup, it takes a huge time to retry to compile, so I've been in this situation in the last days.

Do you think it's possible for you to submit under the Release page a pre-compiled version?

**Comment by M-Reimer** [comment]
Sorry but no. But I'll rework the PKGBUILD this weekend which will result in half the build time

**Comment by jpldcarvalho** [comment]
The only solution was if you remove the need to build wine. But that's not possible.

**Comment by M-Reimer** [comment]
You'll have to build yourself. wine-lol-glibc first. wine-lol second. Don't use AUR helpers for wine-lol. Build with makepkg only.
