### ISSUE TITLE
wine-lol-autoconf-2.70.patch source validation failed.

### ISSUE THREAD

**Issue by dbbvitor** [M-Reimer/wine-lol#71]
I´m trying to install it on an Arch system using yay.
The installation fails with the error:

`==> Validating source files with sha512sums...
    wine-5.6.tar.xz ... Passed
    wine-staging-v5.6.tar.gz ... Passed
    0005-server-Broadcast-rawinput-message-if-request-flag-is.patch ... Passed
    30-win32-aliases.conf ... Passed
    wine-lol-autoconf-2.70.patch ... FAILED
    wine-lol-bug-47198-fix.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
`

**Comment by M-Reimer** [comment]
Can someone please attach the old patch file which still validated?
I don't have the old version and I would have liked to check what exactly changed here...

**Comment by dbbvitor** [comment]
I see you have updated the checksum and it have even hit the aur, but he problem for me continues:
`
==> Validating source files with sha512sums...
    wine-5.6.tar.xz ... Passed
    wine-staging-v5.6.tar.gz ... Passed
    0005-server-Broadcast-rawinput-message-if-request-flag-is.patch ... Passed
    30-win32-aliases.conf ... Passed
    wine-lol-autoconf-2.70.patch ... FAILED
    wine-lol-bug-47198-fix.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
`

Can I help you in anyway?
On the aur page it points to: https://github.com/wine-mirror/wine/commit/d7645b67c350f7179a1eba749ec4524c74948d86.patch

**Comment by M-Reimer** [comment]
Did a try just now and worked well. I guess you have an old version of the wine-lol-bug-47198-fix.patch file somewhere. Update it.

**Comment by gbaranski** [comment]
for me changing back sha512sum to `5ac8e930ca7b15fc7c8945d49885bf06d4608e69c81c3a429020c75e23d641145b9fc346a327d56c3c0d053a4f4f3582e4ef72d59b70460177ec86a018f33195` solved the issue. Using PKGBUILD from git and from aur
