### ISSUE TITLE
wine-lol-glibc from AUR fails

### ISSUE THREAD

**Issue by KDesu9k** [M-Reimer/wine-lol#72]
`In file included from <command-line>:
../misc/syslog.c: In function ‘__vsyslog_internal’:
../misc/syslog.c:127:30: error: inlining failed in call to ‘always_inline’ ‘syslog’: function not inlinable
  127 | ldbl_strong_alias (__syslog, syslog)
      |                              ^~~~~~
./../include/libc-symbols.h:140:26: note: in definition of macro ‘_strong_alias’
  140 |   extern __typeof (name) aliasname __attribute__ ((alias (#name))) \
      |                          ^~~~~~~~~
../sysdeps/generic/math_ldbl_opt.h:14:44: note: in expansion of macro ‘strong_alias’
   14 | #define ldbl_strong_alias(name, aliasname) strong_alias (name, aliasname)
      |                                            ^~~~~~~~~~~~
../misc/syslog.c:127:1: note: in expansion of macro ‘ldbl_strong_alias’
  127 | ldbl_strong_alias (__syslog, syslog)
      | ^~~~~~~~~~~~~~~~~
In file included from ../sysdeps/unix/sysv/linux/syslog.c:4:
../misc/syslog.c:173:3: note: called from here
  173 |   syslog(INTERNALLOG,
      |   ^~~~~~~~~~~~~~~~~~~
  174 |       "syslog: unknown facility/priority: %x", pri);
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [/home/me/Aur/wine-lol-glibc/src/lib32-glibc-build/sysd-rules:213: /home/me/Aur/wine-lol-glibc/src/lib32-glibc-build/misc/syslog.o] Error 1
make[2]: Leaving directory '/home/me/Aur/wine-lol-glibc/src/glibc-2.33/misc'
make[1]: *** [Makefile:479: misc/subdir_lib] Error 2
make[1]: Leaving directory '/home/me/Aur/wine-lol-glibc/src/glibc-2.33'
make: *** [Makefile:9: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...`

➜  ~ pacman -Q glibc
glibc 2.33-4

➜  ~ pacman -Q lib32-glibc
lib32-glibc 2.33-4

Worked fine a couple of days ago reinstalled arch after doing some distro hopping and now I run into this.
Some searching of error: inlining failed to call `always_inline` `syslog`: function not inlinable just turns up a few posts about changing CFLAGS from 2008 they don't seem relevant.

EDIT: Doh I just noticed that wine-lol-glibc is 2.33-1 would that be the reason for this?

**Comment by M-Reimer** [comment]
Just to be sure there are no new issues with building, I did a full rebuild of both, wine-lol-glibc and wine-lol and everything worked well.

Please delete the whole tree you tried to build with, create a completely **fresh**, **empty**, directory. Extract the PKGBUILD files there and do another build this way.

**Comment by AryToNeX** [comment]
This also happens within a "fresh, empty, directory". Just tried it myself and I also made another friend of mine try on a new installation. It happens when using `paru` and when manually compiling with `makepkg -si`. In the folder, nothing else except what it's in the `wine-lol-glibc/` folder of this Git repo.

**Comment by KDesu9k** [comment]
Yep, I tried it again on a fresh Arch install same results.

**Comment by M-Reimer** [comment]
All I can tell is that it worked well for me in a "minimal virtual machine" which only has stuff installed that is needed for building. Nothing more. This concept is similar to what Arch suggests with their builds in a "clean chroot".

I've found your issue here, too:
https://aur.archlinux.org/packages/glibc-dso/

But there is also no information on how to fix it.
Clearly **I** won't be able to do anything to solve this as I can't reproduce it.

**Comment by M-Reimer** [comment]
OK. I thought maybe it could be related to CFLAGS and changes of them in the recent history and it seems like I'm able to reproduce the issue, now.

**Comment by M-Reimer** [comment]
This is a change in makepkg.conf. I usually don't merge updates on my build VM as the makepkg.conf there has some custom changes like special paths where stuff has to be placed to. One change was that fortify was moved from CPPFLAGS to just CFLAGS and so is no longer removed correctly before building glibc.
