### ISSUE TITLE
Compilation broken

### ISSUE THREAD

**Issue by UnsolvedCypher** [M-Reimer/wine-lol#73]
Thank you for your work on this package! I am receiving the following installation error:

```
In file included from <command-line>:
../misc/syslog.c: In function ‘__vsyslog_internal’:
../misc/syslog.c:127:30: error: inlining failed in call to ‘always_inline’ ‘syslog’: function not inlinable
  127 | ldbl_strong_alias (__syslog, syslog)
      |                              ^~~~~~
```

Is this a misconfiguration on my end, or is there an issue with the package itself?

**Comment by M-Reimer** [comment]
NEVER edit out anything in such logs. JUST DON'T DO IT! Now I have to waste time trying this out just to have that full command line...

**Comment by M-Reimer** [comment]
Did a full recompile and had no issue at all. There was a good chance that there is some issue with GCC 11 (many projects failed to build with this update) but not in our case.
