### ISSUE TITLE
LdrInitializeThunk "stub.dll" failed to initialize, aborting

### ISSUE THREAD

**Issue by ItzDerock** [M-Reimer/wine-lol#75]
I'm trying to run League of Legends in a docker container streaming to an X11 server.
My container uses a base image of Ubuntu 20.04 with nvidia cuda support (`nvidia/cuda:11.3.1-cudnn8-runtime-ubuntu20.04`).
`nvidia-smi` seems to output nothing so it's plausible that the container doesn't have gpu support.
Still not sure what `stub.dll` does, and thought maybe someone here knows it's purpose and how I can get it running.

I'm running the following command: `/opt/wine-lol/bin/wine /Game/League\ of\ Legends.exe /Replays/NA1-3926706020.rofl`
and my output is
```
000b:fixme:winediag:start_process Wine Staging 5.6 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
0009:err:module:LdrInitializeThunk "stub.dll" failed to initialize, aborting
0009:err:module:LdrInitializeThunk Initializing dlls for L"Z:\\Game\\League of Legends.exe" failed, status c0000005
```

**Comment by M-Reimer** [comment]
Please forward your question to:
https://www.reddit.com/r/leagueoflinux/
