### ISSUE TITLE
Upgrade to wine 6.10 

### ISSUE THREAD

**Issue by not-wlan** [M-Reimer/wine-lol#76]
https://bugs.winehq.org/show_bug.cgi?id=50868

This bug fix apparently makes the client start way faster. I've tested it briefly and could confirm this. Maybe it could also be backported to 5.6

**Comment by M-Reimer** [comment]
I did a try to get wine 6.10 working. See here:
https://github.com/M-Reimer/wine-lol/tree/wine-6.10
And for me it does not work and I'm not willing to waste even more time.
So I'll not accept this in form of an Issue. Please provide as (tested!) Pull Request. Thanks in advance.

**Comment by M-Reimer** [comment]
Just one small update: I actually did comment in both relevant bugs and did not receive any answer.

That's about as much as I can do. As mentioned several times: I am NO Wine developer so I can't do any fixes in Wine itself.
