### ISSUE TITLE
It says that the wine-lol version that I installed is 32 bit and lol can't open because of that

### ISSUE THREAD

**Issue by ObsidianFury** [M-Reimer/wine-lol#8]
Running /opt/wine-lol/bin/wine /home/mixalhs/Games/league-of-legends/drive_c/Riot Games/League of Legends/LeagueClient.exe
wine: '/home/mixalhs/Games/league-of-legends' is a 64-bit installation, it cannot be used with a 32-bit wineserver.
Waiting on children
All children gone
Exit with returncode 1

Any solution to fix it?

**Comment by M-Reimer** [comment]
According to the Wine wiki "the architecture of an existing WINEPREFIX cannot be changed":
https://wiki.winehq.org/FAQ#How_do_I_create_a_32_bit_wineprefix_on_a_64_bit_system.3F
Seems like the only solution is to reinstall League.

Question is if it's worth to go back to a full featured Wine build just for this. I think reinstalling is a one-time job and it will significantly speed up future rebuilds if the 64 bit stuff doesn't have to be rebuilt.

I think we'll be stuck with a special "wine-lol" for a while...

**Comment by M-Reimer** [comment]
Oh. And if it's Lutris, then they **have to** fix their installation script. LoL is definitively 32 bit only!

**Comment by ObsidianFury** [comment]
So you say to reinstall lol but run it with the patched wine first? or to download the in game content with the pre selected wine version?

**Comment by M-Reimer** [comment]
It won't work with Lutris at all as long as they don't make their WINEPREFIX 32 bit. There is no reason to have it 64 bit. This forces to have a 64 bit wine while LoL is 32 bit only.

I never used Lutris. If it is possible to force Lutris to do the full installation process with wine-lol, then the result will run but I don't think this helper tool will allow you to do this.

If you want to install fully manually, then create a 32 bit WINEPREFIX first:
https://wiki.winehq.org/FAQ#How_do_I_create_a_32_bit_wineprefix_on_a_64_bit_system.3F
Then install d3dx9 with winetricks
And then install LoL into this prefix (you may call the LoL installer with wine-lol at this point)

**Comment by M-Reimer** [comment]
Untested but I googled a bit.

It should just work if you download the Lutris install script and edit the "create_prefix" task to match this script:
https://lutris.net/games/install/8306/view
Means: Add the "arch: win32"
Maybe also add the "arch: win32" to the "game" section at the top of the install file.

If you have enough "arch: win32" in there it should work.
