### ISSUE TITLE
`wine-tkg` branch makes launcher all black

### ISSUE THREAD

**Issue by gbaranski** [M-Reimer/wine-lol#84]
Hi, I've built `wine-tkg` branch, and ran league of legends, unfortunately the whole launcher is black, however I still can move cursor and click buttons.
![image](https://user-images.githubusercontent.com/34353640/131194557-fdc2ce97-2a34-4b36-9ec3-a476f1b4766a.png)

I'm using GNOME Wayland and Arch Linux.

And I launch game using https://github.com/kyechou/leagueoflegends

EDIT: It also happens in GNOME with xorg.

**Comment by RDL-28** [comment]
I have exactly the same problem
archlinux

**Comment by gbaranski** [comment]
Running from lutris solved the issue. It looks like it's https://github.com/kyechou/leagueoflegends fault.

Lutris installer I've used:
https://www.reddit.com/r/leagueoflinux/comments/pc5vao/new_lutris_installer_again/
