### ISSUE TITLE
Custom rune pages have a random chance of disappearing under wine 5.X (recently)

### ISSUE THREAD

**Issue by wiryfuture** [M-Reimer/wine-lol#86]
Within the last week or two, when using wine-lol, there's a chance that my custom rune pages disappear, as they just did for me using the 5.18 build.
This also occurred under lutris-lol so it could be an issue caused by a shared patch which has this unintended side effect, but I suspect it's an upstream wine 5.X bug, as they appear fine every time under wine 6.X.

Under wine-lol or lutris-lol
---
Rune page section in inventory only shows default pages, custom pages are missing, pages may or may not save across sessions. Also, trying to screenshot makes the entite wine window go completely black so I had to use my phone 😬
![PXL_20210828_200632179.jpg](https://user-images.githubusercontent.com/50517631/131230175-dc32c82d-b9c3-4b7e-b173-55700cfd4a57.jpg)

Under wine 6.13
---
Custom rune pages load/appear and save fine (but ofc you can't play on it because it's unpatched 6.x)
![Screenshot_20210828_212459](https://user-images.githubusercontent.com/50517631/131230199-cabf7446-f3e7-49c9-9568-322ac04a5031.png)

**Comment by M-Reimer** [comment]
Actually it doesn't help much having this here. There are **no** Wine developers out there that watch Issues here. This includes me as I'm also no Wine developer and can't debug such things.

Probably open a new Thread about this here: https://www.reddit.com/r/leagueoflinux/
Maybe someone can at least verify if this only happens to you but is a general problem.

**Comment by M-Reimer** [comment]
Replacing "wontfix" with "helpwanted" because maybe someone else wants to use this Issue as discussion platform for fixing this problem. All I want to express is that I won't do anything to fix such issues.

**Comment by M-Reimer** [comment]
Mass closing issues. My PKGBUILD builds a much more recent wine version now so some issues may be obsolete now.
