### ISSUE TITLE
Black window in LoL Launcher

### ISSUE THREAD

**Issue by JoseskVolpe** [M-Reimer/wine-lol#96]
LoL launcher doesn't displays any content and stays black
Procedure:
1. After installing wine-lol, open LoL installer
`/opt/wine-lol/bin/wine 'Install League of Legends br.exe'`
2. Wait for Riot Launcher and LoL Launcher installation
3. Open LoL Launcher and run this script in sequence: https://www.reddit.com/r/leagueoflinux/comments/j07yrg/starting_the_client_script/
4. Wait and ¡bam!...... Black window yey

I've tried the game on plain Wine-staging 6.15 and 6.23 before, both didn't had this issue. 6.23-staging couldn't start the game at all because the patches couldn't be applied, but on Wine-staging 6.15, after setting global variable vsyscall32 to 0 (wich i would like to avoid, that's why i considered wine-lol), the game could start. [More information here](https://appdb.winehq.org/objectManager.php?sClass=version&iId=39897)
I didn't tried WIP wine-lol 6.15 yet, i'll do it later

GPU: Intel HD Graphics 620
Operating System: Manjaro Linux
Kernel: Linux 5.10.85-1-MANJARO
Note: Yes, i did installed Wine Mono (5.1.0) and Wine Gecko (2.47.1)

[shell logs.txt](https://github.com/M-Reimer/wine-lol/files/7766050/shell.logs.txt)

Screenshot:
![Screenshot_20211222_205001](https://user-images.githubusercontent.com/78318343/147173444-8fa33dd1-34da-4c56-8f09-837818812047.png)

**Comment by M-Reimer** [comment]
You are wrong here. I can only support with build errors. Better ask here:

https://www.reddit.com/r/leagueoflinux/

And maybe try my precompiled binary packages.

**Comment by M-Reimer** [comment]
Replacing "wontfix" with "helpwanted" because maybe someone else wants to use this Issue as discussion platform for fixing this problem. All I want to express is that I won't do anything to fix such issues.

**Comment by M-Reimer** [comment]
Mass closing issues. My PKGBUILD builds a much more recent wine version now so some issues may be obsolete now.
